apiVersion: v1
kind: Service
metadata:
  name: nakama
  namespace: playru
spec:
  selector:
    app: nakama
  ports:
  - name: client
    port: 7349
    targetPort: 7349
  - name: http
    port: 7350
    targetPort: 7350
  - name: console
    port: 7351
    targetPort: 7351
  type: ClusterIP
