# Generated by Django 4.2.28 on 2026-02-28 18:12

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nakama_user_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('display_name', models.CharField(max_length=80, verbose_name='Имя игрока')),
                ('avatar_url', models.URLField(blank=True, verbose_name='URL аватара')),
                ('auth_provider', models.CharField(choices=[('vk', 'VK'), ('yandex', 'Яндекс'), ('guest', 'Гость')], default='guest', max_length=20)),
                ('external_id', models.CharField(blank=True, max_length=100)),
                ('total_play_time_minutes', models.PositiveIntegerField(default=0)),
                ('games_played', models.PositiveIntegerField(default=0)),
                ('games_completed', models.PositiveIntegerField(default=0)),
                ('is_banned', models.BooleanField(default=False)),
                ('ban_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Профиль',
                'verbose_name_plural': 'Профили',
                'ordering': ['-last_seen'],
            },
        ),
    ]
