# Generated by Django 4.2.28 on 2026-03-01 07:54

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
        ('platform', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, unique=True)),
                ('dau', models.PositiveIntegerField(default=0, verbose_name='DAU')),
                ('new_users', models.PositiveIntegerField(default=0)),
                ('total_sessions', models.PositiveIntegerField(default=0)),
                ('total_playtime_hours', models.FloatField(default=0.0)),
                ('revenue_rub', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
            ],
            options={
                'verbose_name': 'Статистика платформы',
                'verbose_name_plural': 'Статистика платформы',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='GameSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('nakama_user_id', models.CharField(db_index=True, max_length=100)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.PositiveIntegerField(default=0)),
                ('score', models.PositiveBigIntegerField(default=0)),
                ('completed', models.BooleanField(default=False)),
                ('platform', models.CharField(choices=[('android', 'Android'), ('ios', 'iOS'), ('web', 'Web')], default='android', max_length=20)),
                ('game', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='games.game')),
            ],
            options={
                'verbose_name': 'Игровая сессия',
                'verbose_name_plural': 'Игровые сессии',
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['nakama_user_id', 'started_at'], name='platform_ga_nakama__42225c_idx'), models.Index(fields=['game', 'started_at'], name='platform_ga_game_id_0ef058_idx')],
            },
        ),
    ]
