# Generated by Django 4.2.28 on 2026-02-28 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(verbose_name='Описание')),
                ('short_description', models.CharField(max_length=300, verbose_name='Краткое описание')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='games/thumbnails/')),
                ('nakama_match_label', models.CharField(blank=True, max_length=100)),
                ('lua_module_name', models.CharField(blank=True, max_length=100)),
                ('max_players', models.PositiveSmallIntegerField(default=10)),
                ('min_players', models.PositiveSmallIntegerField(default=1)),
                ('play_count', models.PositiveBigIntegerField(default=0)),
                ('active_players', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('published', 'Опубликована'), ('archived', 'Архив')], default='draft', max_length=20)),
                ('is_featured', models.BooleanField(default=False)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Игра',
                'verbose_name_plural': 'Игры',
                'ordering': ['-play_count'],
            },
        ),
    ]
