# Generated by Django 4.2.28 on 2026-03-01 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='avg_rating',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
        ),
        migrations.AddField(
            model_name='game',
            name='genre',
            field=models.CharField(default='arcade', max_length=30),
        ),
        migrations.AddField(
            model_name='game',
            name='min_age',
            field=models.PositiveSmallIntegerField(default=6),
        ),
        migrations.AddField(
            model_name='game',
            name='ratings_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='game',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='game',
            name='short_description',
            field=models.CharField(blank=True, default='', max_length=300, verbose_name='Краткое описание'),
        ),
        migrations.CreateModel(
            name='GameRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nakama_user_id', models.CharField(db_index=True, max_length=100)),
                ('stars', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('review', models.TextField(blank=True, max_length=500)),
                ('is_approved', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='games.game')),
            ],
            options={
                'verbose_name': 'Оценка игры',
                'indexes': [models.Index(fields=['game', 'is_approved'], name='games_gamer_game_id_25a2cf_idx')],
                'unique_together': {('game', 'nakama_user_id')},
            },
        ),
    ]
