# Generated by Django 4.2.29 on 2026-03-09 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_game_avg_rating_game_genre_game_min_age_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='entry_scene',
            field=models.CharField(blank=True, max_length=200, verbose_name='Точка входа (сцена)'),
        ),
        migrations.AddField(
            model_name='game',
            name='pck_file',
            field=models.FileField(blank=True, null=True, upload_to='games/pck/', verbose_name='PCK файл'),
        ),
        migrations.AddField(
            model_name='game',
            name='pck_hash',
            field=models.CharField(blank=True, max_length=64, verbose_name='SHA-256 хеш'),
        ),
        migrations.AddField(
            model_name='game',
            name='pck_size',
            field=models.PositiveBigIntegerField(default=0, verbose_name='Размер PCK (байт)'),
        ),
        migrations.AddField(
            model_name='game',
            name='pck_version',
            field=models.CharField(blank=True, max_length=20, verbose_name='Версия PCK'),
        ),
    ]
