apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: playru-client
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/YOUR_ORG/playru-client.git
    targetRevision: HEAD
    path: k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: playru
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
