# Generated by Django 4.2.28 on 2026-03-01 13:24

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlayCoinPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=80)),
                ('coins', models.PositiveIntegerField()),
                ('bonus_coins', models.PositiveIntegerField(default=0)),
                ('price_rub', models.DecimalField(decimal_places=2, max_digits=8)),
                ('is_popular', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Пакет PlayCoin',
                'verbose_name_plural': 'Пакеты PlayCoin',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('nakama_user_id', models.CharField(db_index=True, max_length=100)),
                ('status', models.CharField(choices=[('active', 'Активна'), ('cancelled', 'Отменена'), ('expired', 'Истекла'), ('trial', 'Пробная')], default='trial', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('price_rub', models.DecimalField(decimal_places=2, default=149.0, max_digits=8)),
                ('auto_renew', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Подписка Premium',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('nakama_user_id', models.CharField(db_index=True, max_length=100)),
                ('order_type', models.CharField(choices=[('coins', 'Пакет PlayCoin'), ('subscription', 'Подписка Premium')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Ожидает оплаты'), ('paid', 'Оплачен'), ('failed', 'Ошибка'), ('refunded', 'Возврат'), ('cancelled', 'Отменён')], default='pending', max_length=20)),
                ('coins_amount', models.PositiveIntegerField(default=0)),
                ('amount_rub', models.DecimalField(decimal_places=2, max_digits=8)),
                ('payment_provider', models.CharField(default='yukassa', max_length=30)),
                ('payment_id', models.CharField(blank=True, max_length=200)),
                ('payment_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('package', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='monetization.playcoinpackage')),
            ],
            options={
                'verbose_name': 'Заказ',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['nakama_user_id', 'status'], name='monetizatio_nakama__e61d85_idx'), models.Index(fields=['payment_id'], name='monetizatio_payment_b87ab1_idx')],
            },
        ),
    ]
