# Generated by Django 4.2.29 on 2026-03-07 11:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeveloperProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=100, verbose_name='Отображаемое имя')),
                ('bio', models.TextField(blank=True, verbose_name='О себе')),
                ('total_earnings', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Общий заработок')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='developer_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Профиль разработчика',
                'verbose_name_plural': 'Профили разработчиков',
            },
        ),
        migrations.CreateModel(
            name='GameSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('slug', models.SlugField(unique=True, verbose_name='Слаг')),
                ('description', models.TextField(verbose_name='Описание')),
                ('genre', models.CharField(max_length=50, verbose_name='Жанр')),
                ('min_age', models.IntegerField(default=6, verbose_name='Минимальный возраст')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('pending', 'На модерации'), ('approved', 'Одобрена'), ('rejected', 'Отклонена'), ('published', 'Опубликована')], default='draft', max_length=20, verbose_name='Статус')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='Причина отклонения')),
                ('godot_repo_url', models.URLField(blank=True, verbose_name='Godot репозиторий')),
                ('nakama_module_name', models.CharField(blank=True, max_length=200, verbose_name='Nakama модуль')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата отправки')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('developer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games', to='developer.developerprofile')),
            ],
            options={
                'verbose_name': 'Заявка на игру',
                'verbose_name_plural': 'Заявки на игры',
                'ordering': ['-created_at'],
            },
        ),
    ]
