# Generated by Django 4.2.29 on 2026-03-09 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_game_avg_rating_game_genre_game_min_age_and_more'),
        ('developer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesubmission',
            name='game',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submission', to='games.game', verbose_name='Игра в каталоге'),
        ),
    ]
