# Generated by Django 4.2.29 on 2026-03-09 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developer', '0002_add_game_fk_to_submission'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesubmission',
            name='entry_scene',
            field=models.CharField(blank=True, help_text='Например: res://MyGame.tscn', max_length=200, verbose_name='Точка входа (сцена)'),
        ),
        migrations.AddField(
            model_name='gamesubmission',
            name='pck_file',
            field=models.FileField(blank=True, null=True, upload_to='submissions/pck/', verbose_name='PCK файл'),
        ),
    ]
